# Generated by Django 5.0.10 on 2024-12-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb_lite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericobject',
            name='deacription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericobjecttype',
            name='ddescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genericobject',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='genericobjecttype',
            name='attributes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='genericobjecttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]