# Generated by Django 5.0.10 on 2024-12-28 22:10

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_cmdb_lite', '0003_category_genericobjecttype_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericobject',
            old_name='deacription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='genericobjecttype',
            old_name='ddescription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AddField(
            model_name='category',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]